#07/18
SELECT SUM(SAL) FROM EMP;
SELECT DEPTNO, SUM(SAL) FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;

SELECT ENAME, SUM(SAL) FROM EMP
GROUP BY ENAME;

#EMP 테이블에 존재하는 직원의 수는??
SELECT COUNT(*) FROM EMP;

#가장 높은 급여와 가장 낮은 급여를 출력
SELECT MAX(SAL), MIN(SAL ) FROM EMP;

#부서 번호가 20번인 사원의 입사일중 제일 오래된 입사일 출력
SELECT MIN(HIREDATE) FROM EMP
WHERE DEPTNO = 20;

#부서 번호가 30번인 사원들의 평균 급여를 소수점 둘째자리에서 반올림
SELECT ROUND(AVG(SAL),1) FROM EMP
WHERE DEPTNO = 30;

#부서별 평균급여를 소수점 둘째자리에서 반올림 하세요
SELECT DEPTNO, ROUND(AVG(SAL),1) FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;

#부서번호 및 직책별 평균 급여 정렬하기
SELECT DEPTNO, JOB, ROUND(AVG(SAL),1) FROM EMP
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO, JOB;

#GROUP BY 절을 사용하여 부서 번호별 평균 추가 수당을 출력해주세요
SELECT DEPTNO, NVL(AVG(COMM),0) FROM EMP
GROUP BY DEPTNO;

#평균급여가 2000달러 이상인 부서와 직책은?
SELECT DEPTNO, JOB, AVG(SAL) FROM EMP
GROUP BY DEPTNO, JOB
HAVING AVG(SAL) >=2000
ORDER BY DEPTNO, JOB;

#급여가 3000이하이면서 평균 급여가 2000 이상인 부서와 직책 부서와 직책
SELECT DEPTNO, JOB, AVG(SAL) FROM EMP
WHERE SAL <= 3000
GROUP BY DEPTNO, JOB
HAVING AVG(SAL) >= 2000
ORDER BY DEPTNO, JOB, AVG(SAL);

#212P 1번
SELECT DEPTNO, TRUNC(AVG(SAL),0), MAX(SAL), MIN(SAL), COUNT(*) FROM EMP
GROUP BY DEPTNO;

#212P 2번
SELECT JOB, COUNT(*) FROM EMP
GROUP BY JOB
HAVING COUNT(*) >=3 ;

#212P 3번
SELECT TO_CHAR(HIREDATE,'YYYY') AS HIRE_YEAR,DEPTNO, COUNT(*) FROM EMP 
GROUP BY TO_CHAR(HIREDATE,'YYYY'),DEPTNO
ORDER BY HIRE_YEAR;

#212P 4번
SELECT NVL2(COMM,'O','X'), COUNT(*) FROM EMP
GROUP BY NVL2(COMM,'O','X');

#JOIN  테이블의 결합
SELECT * FROM DEPT;
SELECT EMPNO, ENAME, DEPTNO FROM EMP;

#REAL JOIN
#DEPT 4개 * EMP 12개
SELECT * FROM EMP, DEPT;
SELECT COUNT(*)  FROM EMP, DEPT;

#여러분이 사용하는 JOIN 구분
#8-2
SELECT * FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
ORDER BY EMPNO;

#EMP 테이블 별칭을 E DEPT 별칭을 D로 하여
#EMP 테이블의 사원번호와 DEPT 테이블 부서의 이름이
#출력되도록 JOIN 쿼리를 작성해 주세요
SELECT EMPNO, DNAME FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
ORDER BY EMPNO;

#등가조인
SELECT E.EMPNO, E.ENAME, E.DEPTNO, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO;

#239 - 1
SELECT E.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, SAL 
FROM EMP E, DEPT D
WHERE D.DEPTNO = E.DEPTNO AND SAL> 2000;

#239 - 2
SELECT E.DEPTNO, D.DNAME, TRUNC(AVG(SAL),0) AVG_SAL, MAX(SAL) MAX_SAL, MIN(SAL) MIN_SAL, COUNT(*) CNT
FROM EMP E, DEPT D
WHERE D.DEPTNO = E.DEPTNO
GROUP BY E.DEPTNO, D.DNAME;

#연습을 위한 테이블
CREATE TABLE DEPT_SEQUENCE
    AS SELECT * FROM DEPT
       WHERE 1 <> 1;

#테이블 생성 확인
SELECT * FROM DEPT_SEQUENCE;
DESC DEPT_SEQUENCE;
#SEQ 쿼리로 만들기
CREATE SEQUENCE SEQ_DEPT_SEQUENCE
INCREMENT BY 10
START WITH 10
MAXVALUE 90
MINVALUE 0
NOCYCLE
CACHE 2;
#시퀀스 확인
SELECT * FROM USER_SEQUENCES;
#시퀀스 사용
INSERT INTO DEPT_SEQUENCE (DEPTNO, DNAME, LOC)
VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');

SELECT * FROM DEPT_SEQUENCE;
#시퀀스 번호를 확인하기
SELECT SEQ_DEPT_SEQUENCE.CURRVAL FROM DUAL;
#시퀀스 수정
ALTER SEQUENCE SEQ_DEPT_SEQUENCE
 INCREMENT BY 3
 MAXVALUE 99
 CYCLE;
 
COMMIT;

#시퀀스 삭제
DROP SEQUENCE SEQ_DEPT_SEQUENCE;

SELECT * FROM USER_SEQUENCES;
