SELECT * FROM EMP;
#ENAME과 job, sal를 출력하괴 sal 기준으로 오름차순 정렬
SELECT ENAME, JOB, SAL FROM EMP
ORDER BY SAL DESC;

#부서(DEPT) 테이블을 조회
SELECT * FROM DEPT;
SELECT * FROM DEPARTMENTS;
SELECT MGR FROM EMP;
#MGR값 중 고유한 값만 출력
SELECT DISTINCT MGR FROM EMP;
#월급(SAL)에 12를 곱하여 연볼 구하기
SELECT ENAME AS 이름, SAL 월급, SAL*12 AS 연봉 FROM EMP;
#부서번호가 30번인 부서원의 모든 정보
SELECT * FROM EMP
WHERE DEPTNO = 30;
#사원 번호가 7782인 사원의 정보를 출력
SELECT * FROM EMP
WHERE EMPNO = 7782;

#부서 번호가 30번 이면서 직업이 SAL인 직원들은?
SELECT * FROM EMP
WHERE DEPTNO = 30 AND JOB = 'SALESMAN';
#사원 번호가 7499이고 부서번호가 30번인 사원 정보
SELECT * FROM EMP
WHERE EMPNO = 7499 AND DEPTNO = 30;
#부서번호가 30, 또는 직업이 'CLERK'인 사원정보는?
SELECT * FROM EMP
WHERE DEPTNO = 30 OR  JOB = 'CLERK' ;
#급여가 3000 이상인 사원정보는?
SELECT * FROM EMP
WHERE SAL >=2000;
#급여가 2500이상이고 직업이 'ANALYST'인 사원 정보는?
SELECT * FROM EMP
WHERE SAL >= 2500 AND JOB ='ANALYST';
SELECT * FROM EMP
WHERE ENAME >='F';
#급여가 3000이 아닌 사람은 어떻게 표현?
SELECT * FROM EMP WHERE SAL != 3000;
SELECT * FROM EMP WHERE SAL <> 3000;
SELECT * FROM EMP WHERE SAL ^= 3000;
SELECT * FROM EMP WHERE NOT SAL = 3000;
#IN연산자 포함
#직업이 'MANAGER' 또는 'SALESMAN' 또는 'CLERK'
SELECT * FROM EMP
WHERE JOB IN ('MANAGER' , 'SALESMAN' , 'CLERK');
#전체 부정
SELECT * FROM EMP
WHERE JOB NOT IN ('MANAGER' , 'SALESMAN' , 'CLERK');
#등가비교 (OR)을 이용해서 동일하게 만들려면
SELECT * FROM EMP
WHERE JOB != 'MANAGER'  AND JOB <> 'SALESMAN' AND JOB ^= 'CLERK';

BETWEEN A AND B
#급여가 2000이상 3000이하
SELECT * FROM EMP
WHERE SAL BETWEEN 2000 AND 3000;
SELECT * FROM EMP
WHERE SAL >= 2000 AND SAL <= 3000;
#문자열 포함
SELECT * FROM EMP
WHERE ENAME LIKE 'S%';

#사원 이름의 두 번째 글가자 L인 사원만 출력하세요
SELECT * FROM EMP
WHERE ENAME LIKE '_L%';


#사원 이름에 AM문자가 포함되어 있는 사원 데이터 출력
SELECT * FROM EMP
WHERE ENAME LIKE '%AM%';


